flyway.url=jdbc:postgresql://aws-1-sa-east-1.pooler.supabase.com:6543/postgres?sslmode=require
flyway.user=postgres.vcxvgbhyctozfqotnaik
flyway.password=Projetowanderson2012
flyway.schemas=public
flyway.locations=filesystem:./migrate
flyway.connectRetries=10
flyway.connectRetriesInterval=15
flyway.validateOnMigrate=true